name: PlatformIO CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
            ~/.pio
          key: ${{ runner.os }}-pio-${{ github.sha }}
          restore-keys: ${{ runner.os }}-pio-
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install platformIO libraries
        run: pio pkg install
      - name: Build PlatformIO Project
        run: pio run

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware.bin
          path: .pio/build/m5stack-core2/firmware.bin